replicaCount: 2

image:
  repository: 724793286760.dkr.ecr.ap-south-1.amazonaws.com/ml-inference
  tag: "1.0.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics