replicaCount: 2

image:
  repository: 724793286760.dkr.ecr.ap-south-1.amazonaws.com/ml-inference
  tag: "a803e1407dea22c135da802817a3e644cb790422"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics