name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::724793286760:role/mlops-dev-github-actions-role
          aws-region: ap-south-1
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -v

      - name: Build Docker image
        run: docker build -t ml-inference:${{ github.sha }} ./app

      - name: Tag Docker image
        run: |
          docker tag ml-inference:${{ github.sha }} \
            724793286760.dkr.ecr.ap-south-1.amazonaws.com/ml-inference:${{ github.sha }}
